name: Deploy to Production
on: [push]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Pull on VPS and restart
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          cd /root/disq/site 
          git pull 
          ~/.nvm/versions/node/v15.14.0/bin/yarn
          ~/.nvm/versions/node/v15.14.0/bin/yarn build
          ~/.nvm/versions/node/v15.14.0/bin/pm2 restart disq_site